videoApi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    # This route will forward every request with `/video` to
    # videoApp application of this project.
    path('video/', include('videoApp.urls'), name='videoApp')
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

videoApp/urls.py
from django.urls import include, path
from . import views
from . import viewsApi

app_name = 'videoApp'
urlpatterns = [
    # Api endpoints
    # Views are defined in ./viewsApi.py file
    path('api/upload/', viewsApi.upload, name='apiUpload'),
    path('api/listUploading/', viewsApi.listUploading, name='apiListUploading'),
    path('api/charge/', viewsApi.charge, name='apiCharge'),
    path('api/', viewsApi.listUploaded, name='apiListUploaded'),
    path('', views.index, name='apiIndex'),
]

videoApp/models.py
from django.db import models
from .utils import validator


class Video(models.Model):
    id = models.BigAutoField(primary_key=True)
    title = models.CharField(max_length=200, default="Video Title")
    videoSummary = models.TextField(default="Video Summary")

    type = models.CharField(max_length=100, default="mp4")

    # Actual binary data is stored as FileField in static/uploads
    # Since I'm using Sqlite here
    # We can hit some cdns to handle media files for serious projects
    # Or some other database that supports raw binary data storage natively
    # Like the MongoDB with GridFsStorage
    data = models.FileField(
        upload_to="uploads/", max_length=250, validators=[validator.validateVideo])

    # Timestamps
    created = models.DateTimeField(auto_now_add=True, editable=False)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

videoApp/views.py
from django.http import HttpResponse
from django.shortcuts import render
from . import models


def index(request):
    return render(request, "videoApp/upload.html")
    return render(request, "videoApp/index.html", {"videos": models.Video.objects.all()})

videoApp/templates/videoApp/index.html
{% load static %}
<!DOCTYPE html>
    <head>
        <title>
            Video App
        </title>
        <style>
            body{
                display: flex;
                justify-content: center;
                align-items: center;
                gap: 1em;

                background-color: antiquewhite;
            }
            .video_item{
                padding: 1em;
                border: 3px solid aqua;
                border-radius: 1em;
            }
        </style>
    </head>
    <body>
        {% for i in videos %}
            <div class="video_item">
                <video controls width="700" height="500">
                    <source src="{{ i.data.url }}">
                </video>
            </div>
        {% endfor %}
    </body>
</html>

videoApp/templates/videoApp/upload.html
<!-- 
    How the uploading works:
    you first send a GET request that requests a videoId to keep track of videos being uploaded
    then you submit a form with that received id to upload the video at once

    Note: It's non resumable upload and is not recommended
          Implement chunked upload in production
-->
<!DOCTYPE html>
    <head>
        <title>
            Video App
        </title>
        <style>
            body{
                display: flex;
                justify-content: center;
                align-items: center;
            }
            form{
                display: flex;
                flex-direction: column;
                gap: 1em;

            }
            form *{
                padding: .5em;
                text-align: center;
            }
            button{
                border: 0;
                border-radius: 1em;
                background-color: rgb(223, 112, 78);
            }
            button:hover{
                transform: scale(1.1);
                transition: .3s;
            }
        </style>
        <script>
            function postForm(){
                const f = document.getElementById("Form")
                const form = new FormData(f);
                fetch(f.attributes.action.textContent, {
                    method: "PUT",
                    headers: {
                        'Content-Type': 'application/json' 
                    },
                    body: JSON.stringify({
                        title: form.get("title"),
                        summary: form.get("summary")
                    })
                }).then(async (res) =>{
                    const r = await res.json()
                    f.children.videoId.value = r["videoId"]
                    f.submit()
                }).catch(e => {
                    alert(e)
                })
            }
        </script>
    </head>
    <body>
        <form enctype="multipart/form-data" action="{% url 'videoApp:apiUpload'%}" id="Form" method="POST">
            <input type="number" name="videoId" hidden>
            <label for="title">Title: <input type="text" name="title" value="Title"></label>
            <label for="summary">Summary: <input type="text" name="summary" value="Summary"></label>
            <input type="file" name="data">
            <button type="button" onclick="postForm()">Upload</button> 
        </form>
    </body>
</html>